language: node_js
node_js: '8'
jobs:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - docker
      env:
        global:
        - BUILD_OS: "linux"
        # Test1 - no --pro quoted
        - secure: "n6SNdnywYTcfTeI3SSNJRvEmav9lNILSUnneeJ8ensHjSUWwtPIArJT9TcSFoUXARC+0QkKiP0TYLSdMbnnyUSA8+dDORT+FPsR6qzfqg1V7edTpojN8nGp5qHCkZPuNhzmSfvazFxPCDzOOZ9fotETCdsR7CiS30NRyE9h1aD26m4YmwDtqf+1n5Y+3CkGcQLo4LhMk2xAy14/ci5/d+y6fcN/5LWcDNT/CI5c0OjfEfcUOurz6LwhXM0rasbHGFZAZeUIFmofKycvQzFWCAlVKk533VUvJbBqP/vjuHETFjtyRk1eoe4C4Mf2w8XpLy4odb8NU8S8AEIL6JSZHJlXX32+l5K4zAvOnW1S/jU5tFP7B4EEUBX3GDuski+sRIFZqTmQqTWUakPZheFx2Qmp0fgoxURzLIefKeZHIU3qX6N6Q58BxARMfJT1JCIqLacGYlUkn8dO5182C8a+ceUPayBJ7/LZdvzfwmSt91TMv5tx3GtcmssNHg6tCfRt+IwrgaDmLpsseIom2hlzLVOtCBTr348vj5FSt84dmGUb9F0e8CoOjAcv4RL1pDvlRZHJcSzk/yQsqm5Pp4FugCBaElIxfXlProf504hMa1Ufg3DTMZ+v4+OWKTiOKPxN8OrNvZdunXW6mINe202Zl4cf0Z0YHPCZ2TnSskP/zRxg="
        # Test2 - no --pro
        - secure: "glGPOol3IVqmSxdtjU9IS5BP/UFAgCYWPMhWXItVKpRHe7zxy5JdGuyeEoRk4WOcF2dH79HaWoZCy2PCQ8HPnprBOdUgQZq8EwKbGyMm7+S3zTFwMU4R6kjnGdzDPrrzm8un6JuJwxcMi+OamXAXx7y3GXCFQy6uBBZTiCjGZCD/VFHF1Z/ekc4LNYxa55lYCuc3YKG4M1EMXpMuPCEuhmLQF9PKrs7rjrRXuIhShhRnF7afKXgktWKDdXtoC9Hp81xLez/NEVl+UE9M+k7tvCtIqAV9YhrcdxtWAI0lkkwrS0mM5mANd51C0bbQUPfaSJiGViFnI8cbjKTfPVX0xLoVgHAAek/BJE1jGvhqEpuXKzeuDj3RRgxRyjHxTBpYwKtb+QwsHpgD30I5i/PixkoQjIaYCBnyZQQsEfAGmBFROFsieOBVfknkLr20N97OWisy3NEk4jgVISgQBiIPbyS16bdAh/Df1ARBYaklrEDwxB1XOVswXKKWm16enHZbzWZj0zt2gLM0AUZBjHt0ap+t4awviXAO69iZTXrxoujfIhjQYtaavp02UM6F/X/OPa7kUUmzqvCYzjARJ0esW85IAicvKZUV/5l6esvuXrnebkS6/ChfxX743Lnw0bdGtK79a4KAmrPkuFd37KFNzRohv5s76P0KirYQPPiUz9s="
        # Test3 - with --pro quoted
        - secure: "rIUb4Mk21FhoHuGu2//II/AEqqxbUJrSZ377B07tr8F6y0jNex3NN74lgfjFXLjiChQIK5iAPWg/jyDKS5OGoytgwrKOfBcc1p0v1Yd8qu6JPc2iPmvMUPiqUIdk0Xx36y+mucwGDKkAdsPg/UjHqMOBnyqCyEFPVkAMV7k3wWH8C7Napklj08iDlEUOiT2CylfUBEsgYG1honzQyK7crBOS+cI+87aNDbg6MmGZav9F+EOqy4AB8iLZSXVYCFDErFWUDyoXK9T/px2rQZ7mUA8/7Ubewzo8szYVrzuF7o3GVURUt5RHjfla2HJ9s5hqxeZkI91jVlGsZuLGncv/IfozIIRKl/QmIGtBB5FOW1ZkyQ24TMti7YdJW+hwr4vrOy6tZhAROa7ochhiFoVVmeFJVYAC4Oiur4pJny1pPAF7l/LikOde6plsyK1r9rQht+ngJrfcktzoRLMNLvYWkytUhFzAraBKY6i/R74ajw1LLEHAFqpcxIeRuCt+Wtu+Sxz8cdoJxVWsqozwXsirbN90ATaZnp+Qx8w3ZaByCkqh6PNt+UcAZjJOr8E+/JychwIbebfKU4J8YDAk277wzNlaM4Odub6rXnbbXJrQULKsnkXUw1te3mcpjW47axuMU/0BqTVnC1ZW2wY3UQrEqcNBOP6lsD7PREaLOTAWHdA="
        # Test 4 - with --pro
        - secure: "Qm8ZS8MoQAhNSeaM9lUpIDS5ml68Z5XzCPdwQ+XO58VmeBKqQfprhA1q9lWD2KXUjUx/hhtVv4PcgJmW6kxd7bEoSFzuqu7GOmfC4f+ykkdKr9QjVH1mpZDT+IdqRROTL3oXFm/Bu54Bb210vLoywLQsdsEy5eSLtMVgwpnxq9OlDsPIgjqWHO6Y5xONVX9m3b+sGCUyMEnv0QhUc0/qcUwXow37cpX+bZT353ES4DPxHHRY5Cru5HSWkNQ7SdOWkoN2AeKgPnEFVgTQHFSU8iwYN5kUt2EhZ3BcqiOqPS2WdTpK8rBnFzTtY+CrYbmPvBY8+Z8bvO0ogtXtBWU6SnHsKNx3h9rr3sbV+0LPFI7GQBNs9/zMxFrWyD4F+cuaKw9TYRJVDWazha7sITCv8yNf+kLT+hsgFjQBt+/OGOg0YKksKkskVJV84RDqnZKB8EnnMDVDWBhKYyuYMqh+0EMsX8q0sVWg+25BzQeaMqpd9OoSRr9c1s/QlJncLgVzrAb2fEnsbgfXADoHuDZC1Ual2xqr7f01ljPw9vo5BZwjrvAA9ptzgb/zJWNjHjD0XpN9L5wKHEDMtW9kwA684sZAld+Rx8NDafxvrd6PNfE52h7koTbJekV92Ovlqwdb8xXRcCCz7Z0n9rNmbEv1bq87MU2lmtzzMasbcpCWPpI="

    # - os: osx
    #   compiler: clang
    #   osx_image: xcode11.2
    #   env:
    #     global:
    #     - BUILD_OS: "osx"
    #     - APP_IDENTITY: "C2E24BC6719F81C54FAD02B8B4E3535B330794B8"
    #     # CERT_PASS
    #     - secure: "R9IDvyVJ8mQ5gpcqMu2XSv02AQVDcTla0S85NfQJ0jJU+rmOYwdUO4nT9a2nMN3bwtcRUpSi4AUiYZ7oiN/Aia/0SCiM0gfU3gQ3umuaRuIJ82C4ILkF/1ez021koF5pNDqFhw6YrL5lXi2RwpUDaAhfZO93kM4/e9y4r8jAEwU8NN+p6fSH8FQLuam7LSVDTLZaEdgBZfMEczPvGq+MztI6Kg4qtpHNC3fgzlXDwUjlHlQU6dqf5fuhMbhthcDTCWYND0A+Tc3sT9m3rRfXQvSbiXExzgA7+rra73CKT5jcZ2q2u8PihfH9HWzjrNBjNxey2NdHYI/i2C2mTM4+bX3C8BtlS9eTmeodRfXbw5dRtLh04d7i2qnzvZTzi7N04O6w0sgIGlnWI/GPm6c+6uJ4KoOi04OmPqER7+u+PRWTv1jiD3u3qe9cBHpdy9YHZswjqSpZKXkw+jBstEUz/rrL+tMTJZTGPj9Mmw25Zx+6SkTwQKTR3ysAV67L43W8ZHw7Tt8qOMfwCjCyAWBA9aVKUW+NZDb5ZGb5XVue8v3XKPXm4crICtX1nqOR2qHyvIaIKIzKtvcpIhOmIYEREyfrI1PRVixZluDTad6+yK+ISFH+Wxbbsi714e/V1M0GWKq349sRDqb52uW6+h3Nro99KT31L8/+XkTX2WpP86Y="
    #     # AWS_SECRET
    #     - secure: "CpL6ITYa53WGTi1rBMcTwdxcqEoZkli6lgy8sTQjvqD5aXAwq1BT/LCZf3/8OE+9a4g9izy5l4Eb6qZRcuG3v1FSBssUvzDBKECdR5vy9jeewgMbpnkWtszAhrpqtBT37OG72Dm94LfObQh2cagUJpDYuVDAesBC4OQmBm9n+HrG3YmUWxrP6tEnN/ngf2XhCbCCTTC3be42JWdhtX6ufAJ+oGanC/ryptac/qufJQ3MgchuxEBDsLKVXeb/OQB8UHrrubBmxzRHgqKk/VpAtZ88DerF4LaJ+1RL13JEamVeBbQY9de0Un0QPi+eZSjfY9JB13GmZh0sv2kHY0w1Awn0SmYpNeKzwbcFhEawI7gTa3j0r9CK6IysZ/Vbi0rox/V4EddW6IB3FetOdcYSq00TbOy1hmg6f/58PMs+kZZ0t0J5SVke0u/Kts1wuK6QUpacqrdoCnc8xrf/q3z3PVTVMyusP+2oi4ULp5VoJDmZd6TQN61nN3ynaFEUOzow7ZNfO3w2BrK1kf2HU+TwX3TWfFOZZbQ8wQrzWDyx8IfpTNPRvfYf+RgqSyVlUdjfN42wY0G44KT03mnBaJT1L8KGKfaNkBLwsh0vu/YU7/fGbDwUvVGvhhqfnQbzJ6PVEuozE3AaX7pm6t7pWZe6X5TUg1RVBc2bJY3h+x04m2s="

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install p7zip awscli; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm -g install appdmg; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source ./mac/keychain_profile; fi
  - sudo pip install --upgrade s3cmd

install:
  - echo "Nothing to do for install"
  
script:
  - export NODE_BIN_PATH=$(dirname `which node`)
  # Set environment
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source mac/mac_profile; fi

  - mkdir -p packages
  - export DESTDIR=`realpath packages`
  - export BRANGCH=$(git rev-parse --abbrev-ref HEAD)
  - export TAG=${TAG:-$TRAVIS_BRANCH}
  - echo "> building from TAG $TAG"
  - echo "> Using node $(node --version)"
  # - git checkout $TAG

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export DISTROS=`ls distros`; for i in $DISTROS; do echo "Building for distro $i..." && ./dist-utils/build-package.sh $i -d $DESTDIR -t $TAG; done fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ( qmake . && make ); fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./mac/finalize.sh "$TAG"; fi

  # Test if the app launches
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ( ./stremio.app/Contents/MacOS/stremio & sleep 10 && STREMIO_PID=$! && kill $STREMIO_PID ); fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./mac/pack.sh; fi

  # Upload artifacts
  - export AWS_ACCESS_KEY_ID="AKIAJWBFLU34IVITPLHA"
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET
  - export AWS_DEFAULT_REGION=eu-west-1
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then s3cmd --acl-public --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY --force --region=$AWS_DEFAULT_REGION --add-header=Cache-Control:max-age=7200 put ./dist-osx/*.dmg s3://stremio-artifacts/shell-osx-old/$TAG/; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then shopt -s nullglob; for package in $DESTDIR/*.{deb,pkg.tar.xz,rpm}; do echo Uploading package to http://stremio-artifacts.s3.amazonaws.com/shell-linux/$TAG/$package; s3cmd --acl-public --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY --force --region=$AWS_DEFAULT_REGION --add-header=Cache-Control:max-age=7200 put "$package" s3://stremio-artifacts/shell-linux/$TAG/; done; fi

  # notifications:
  #   slack: 
  #     rooms:
  #       - stremio:74vRvYUJbhcl3IrYCbOIvTo3#installer-ci
  #     template: |
  #       %{repository}@%{branch}: build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}
  #       %{message} - %{commit_message}"
